# Generated by Django 4.2.6 on 2023-10-23 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('DNICliente', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=15)),
                ('historial_cliente', models.TextField()),
                ('anotaciones', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Hormigon',
            fields=[
                ('IdHormigon', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Modulos',
            fields=[
                ('IdModulos', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('IdObra', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('IdPedido', models.AutoField(primary_key=True, serialize=False)),
                ('NombreyApellidoCliente', models.CharField(editable=False, max_length=200)),
                ('FechaDeEntrega', models.DateField()),
                ('CantidadM3', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ValorTotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('EstadoPedido', models.CharField(max_length=50)),
                ('DNICliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tesisApp.cliente')),
                ('IdHormigon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tesisApp.hormigon')),
                ('IdObra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tesisApp.obra')),
            ],
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('DNI', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=15)),
                ('clave', models.CharField(max_length=128)),
                ('IdModulos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tesisApp.modulos')),
            ],
        ),
    ]
