# Generated by Django 4.2.6 on 2023-10-23 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tesisApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Empleados',
            new_name='Empleado',
        ),
        migrations.RenameModel(
            old_name='Modulos',
            new_name='Modulo',
        ),
    ]
