# Generated by Django 4.2.6 on 2023-10-23 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesisApp', '0002_rename_empleados_empleado_rename_modulos_modulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='IdHormigon',
        ),
        migrations.AddField(
            model_name='pedido',
            name='Hormigones',
            field=models.ManyToManyField(to='tesisApp.hormigon'),
        ),
    ]
