# Generated by Django 4.2.6 on 2023-10-23 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tesisApp', '0003_remove_pedido_idhormigon_pedido_hormigones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='ValorTotal',
        ),
    ]
