# Generated by Django 4.2.6 on 2023-10-23 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesisApp', '0004_remove_pedido_valortotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='EstadoPedido',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Preparacion', 'Preparación'), ('Cancelado', 'Cancelado'), ('EnCamino', 'En Camino'), ('Entregado', 'Entregado')], default='Pendiente', max_length=50),
        ),
    ]
