# Generated by Django 4.2.6 on 2023-10-23 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesisApp', '0005_alter_pedido_estadopedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='EstadoPedido',
            field=models.CharField(max_length=50),
        ),
    ]
