# Generated by Django 4.2.6 on 2023-10-24 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesisApp', '0007_alter_pedido_estadopedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='clave',
            field=models.CharField(max_length=20),
        ),
    ]
