# Generated by Django 4.2.6 on 2023-11-07 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesisApp', '0009_remove_cliente_anotaciones_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='IdModulos',
        ),
        migrations.AddField(
            model_name='empleado',
            name='rol',
            field=models.IntegerField(choices=[(0, 'Gerente'), (1, 'Logística'), (2, 'Plantista'), (3, 'Transportista')], null=True),
        ),
        migrations.DeleteModel(
            name='Modulo',
        ),
    ]
