# Generated by Django 4.2.6 on 2023-11-07 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesisApp', '0012_remove_empleado_clave_alter_empleado_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='rol',
            field=models.IntegerField(choices=[(0, 'Gerente'), (1, 'Logística'), (2, 'Plantista'), (3, 'Transportista'), (4, 'Administracion')]),
        ),
        migrations.AlterField(
            model_name='obra',
            name='direccion',
            field=models.CharField(max_length=150),
        ),
    ]
